# This is a basic workflow that is manually triggered
name: Teste Azure MySQL Server

on:
  workflow_dispatch:
    inputs:
      server:
        description: 'Servidor a testar'
        default: '---'
        required: true
        type: string
      query:
        description: 'Query teste (ficheiro .sql)'
        default: 'create.sql'
        required: true
        type: string

jobs:
  test-mysql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositório
      uses: actions/checkout@v4

    - name: Verificar ficheiros no diretório
      run: ls -l

    - name: Instalar cliente MySQL
      run: sudo apt-get update && sudo apt-get install -y mysql-client

    - name: Executar query no servidor MySQL
      env:
        MYSQL_HOST: ${{ inputs.server }}
        MYSQL_USER: gestor
        MYSQL_PASSWORD: Abcd123!
        MYSQL_QUERY_FILE: ${{ inputs.query }}
      run: |
        echo "Conectando ao servidor MySQL: $MYSQL_HOST"
        mysql -h "$MYSQL_HOST" -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" < "$MYSQL_QUERY_FILE"tor -p'Abcd123!' 
