name: Conectar Postgre

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Servidor a testar'
        default: '---'
        required: true
        type: string

jobs:
  testar-postgre:
    runs-on: ubuntu-latest
    environment: database-test

    steps:
      - name: Instalar cliente PostgreSQL
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Verificar conexão com PostgreSQL
        env:
          PGHOST: ${{ inputs.name }}
          PGPORT: 5432
          PGDATABASE: postgres
          PGUSER: ${{ secrets.USER }}
          PGPASSWORD: ${{ secrets.PASS }}
        run: |
          echo "Conectando ao servidor PostgreSQL: $PGHOST"
          psql -h "$PGHOST" -U "$PGUSER" -d "$PGDATABASE" -c "SELECT version();"
