# This is a basic workflow that is manually triggered

name: Conectar Postgre

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Servidor a testar'
        default: '---'
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    environment: database-test

    steps:
      - name: Enviar saudação
        run: echo "Hello ${{ inputs.name }}"

      - name: Testar ligação ao PostgreSQL
        env:
          PGHOST: ${{ inputs.name }}
          PGPORT: 5432
          PGDATABASE: postgres
          PGUSER: ${{ secrets.USER }}
          PGPASSWORD: ${{ secrets.PASS }}
        run: |
          echo "Conectando ao servidor PostgreSQL: $PGHOST"
          psql -c "SELECT version();"
    
